const TRACKING_WEAN_ACTIONS = {
  FETCH_WEAN_NOTES_LOADING: "FETCH_WEAN_NOTES_LOADING",
  FETCH_WEAN_NOTES_SUCCESS: "FETCH_WEAN_NOTES_SUCCESS",
  FETCH_WEAN_NOTES_ERROR: "FETCH_WEAN_NOTES_ERROR",
  REFRESH_WEAN_NOTES: "REFRESH_WEAN_NOTES",
  SHOW_WEAN_NOTES_MODAL: "SHOW_WEAN_NOTES_MODAL",
  FETCH_WEAN_NOTE_DETAIL_LOADING: "FETCH_WEAN_NOTE_DETAIL_LOADING",
  FETCH_WEAN_NOTE_DETAIL_SUCCESS: "FETCH_WEAN_NOTE_DETAIL_SUCCESS",
  FETCH_WEAN_NOTE_DETAIL_ERROR: "FETCH_WEAN_NOTE_DETAIL_ERROR",
  FETCH_MATERIAL: "FETCH_MATERIAL",
};

export default TRACKING_WEAN_ACTIONS;
