const TRACKING_VACCIN_ACTIONS = {
  FETCH_VACCIN_NOTES_LOADING: "FETCH_VACCIN_NOTES_LOADING",
  FETCH_VACCIN_NOTES_SUCCESS: "FETCH_VACCIN_NOTES_SUCCESS",
  FETCH_VACCIN_NOTES_ERROR: "FETCH_VACCIN_NOTES_ERROR",
  REFRESH_VACCIN_NOTES: "REFRESH_VACCIN_NOTES",
  SHOW_VACCIN_NOTES_MODAL: "SHOW_VACCIN_NOTES_MODAL",
  FETCH_VACCIN_SHOT_LOADING: "FETCH_VACCIN_SHOT_LOADING",
  FETCH_VACCIN_SHOT_SUCCESS: "FETCH_VACCIN_SHOT_SUCCESS",
  FETCH_VACCIN_SHOT_ERROR: "FETCH_VACCIN_SHOT_ERROR",
};

export default TRACKING_VACCIN_ACTIONS;
