const TRACKING_WEIGHT_ACTIONS = {
  FETCH_WEIGHT_NOTES_LOADING: "FETCH_WEIGHT_NOTES_LOADING",
  FETCH_WEIGHT_NOTES_SUCCESS: "FETCH_WEIGHT_NOTES_SUCCESS",
  FETCH_WEIGHT_NOTES_ERROR: "FETCH_WEIGHT_NOTES_ERROR",
  REFRESH_WEIGHT_NOTES: "REFRESH_WEIGHT_NOTES",
  SHOW_WEIGHT_NOTES_MODAL: "SHOW_WEIGHT_NOTES_MODAL",
  FETCH_WEIGHT_NOTE_DETAIL_LOADING: "FETCH_WEIGHT_NOTE_DETAIL_LOADING",
  FETCH_WEIGHT_NOTE_DETAIL_SUCCESS: "FETCH_WEIGHT_NOTE_DETAIL_SUCCESS",
  FETCH_WEIGHT_NOTE_DETAIL_ERROR: "FETCH_WEIGHT_NOTE_DETAIL_ERROR",
};

export default TRACKING_WEIGHT_ACTIONS;
