const STORIES_ACTIONS = {
  FETCH_STORY_LIST_LOADING: "FETCH_STORY_LIST_LOADING",
  FETCH_STORY_LIST_SUCCESS: "FETCH_STORY_LIST_SUCCESS",
  FETCH_STORY_LIST_ERROR: "FETCH_STORY_LIST_ERROR",
  SET_SHOW_MODAL: "SET_SHOW_MODAL",
  UPLOAD_STORY_LOADING: "UPLOAD_STORY_LOADING",
  UPLOAD_STORY_SUCCESS: "UPLOAD_STORY_SUCCESS",
  UPLOAD_STORY_ERROR: "UPLOAD_STORY_ERROR",
  LIKE_STORY: "LIKE_STORY",
  DISLIKE_STORY: "DISLIKE_STORY",
  GET_LIKERS_SUCCESS: "GET_LIKERS_SUCCESS",
  GET_LIKERS_LOADING: "GET_LIKERS_LOADING",
  SHOW_LIKER_MODAL: "SHOW_LIKER_MODAL",
  SET_LIKER_STORY: "SET_LIKER_STORY",
  TRIGGER_FETCH_STORIES: "TRIGGER_FETCH_STORIES",
  UPDATE_LOADING_STORIES: "UPDATE_LOADING_STORIES",
  RESET_STORY_LIST: "RESET_STORY_LIST",
  DETELE_STORY: "DETELE_STORY",
  FETCH_STORY_DETAIL: "FETCH_STORY_DETAIL",
  FETCH_STORY_DETAIL_LOADING: "FETCH_STORY_DETAIL_LOADING",
};

export default STORIES_ACTIONS;
