const CHAT_ACTIONS = {
  FETCH_CONVERSATIONS_LOADING: "FETCH_CONVERSATIONS_LOADING",
  FETCH_CONVERSATIONS_ERROR: "FETCH_CONVERSATIONS_ERROR",
  SET_CURRENT_CONVERSATION: "SET_CURRENT_CONVERSATION",
  UPDATE_CONVERSATION: "UPDATE_CONVERSATION",
  UPDATE_MESSAGE_STATUS: "UPDATE_MESSAGE_STATUS",
  UPDATE_MESSAGE_DATA: "UPDATE_MESSAGE_DATA",
  UPDATE_PAGINATION_DATA: "UPDATE_PAGINATION_DATA",
  UPDATE_SINGLE_USER_MESSAGES: "UPDATE_SINGLE_USER_MESSAGES",
  UPDATE_SINGLE_USER_SINGLE_MESSAGE: "UPDATE_SINGLE_USER_SINGLE_MESSAGE",
  UPDATE_SERIAL_USER_MESSAGES: "UPDATE_SERIAL_USER_MESSAGES",
  TRIGGER_SCROLL_BOTTOM: "TRIGGER_SCROLL_BOTTOM",
};

export default CHAT_ACTIONS;
