const ACTIVITY_TRACK_ACTIONS = {
  FETCH_STD_HEIGHT_LOADING: "FETCH_STD_HEIGHT_LOADING",
  FETCH_STD_HEIGHT_MAX_SUCCESS: "FETCH_STD_HEIGHT_MAX_SUCCESS",
  FETCH_STD_HEIGHT_MIN_SUCCESS: "FETCH_STD_HEIGHT_MIN_SUCCESS",
  FETCH_STD_HEIGHT_ERROR: "FETCH_STD_HEIGHT_ERROR",
  FETCH_STD_WEIGHT_LOADING: "FETCH_STD_WEIGHT_LOADING",
  FETCH_STD_WEIGHT_MAX_SUCCESS: "FETCH_STD_WEIGHT_MAX_SUCCESS",
  FETCH_STD_WEIGHT_MIN_SUCCESS: "FETCH_STD_WEIGHT_MIN_SUCCESS",
  FETCH_STD_WEIGHT_ERROR: "FETCH_STD_WEIGHT_ERROR",
};

export default ACTIVITY_TRACK_ACTIONS;
