const BLOCKED_USER_ACTIONS = {
  FETCH_BLOCKED_USERS_LOADING: "FETCH_BLOCKED_USERS_LOADING",
  FETCH_BLOCKED_USERS_SUCCESS: "FETCH_BLOCKED_USERS_SUCCESS",
  FETCH_BLOCKED_USERS_ERROR: "FETCH_BLOCKED_USERS_ERROR",
};

export default BLOCKED_USER_ACTIONS;
