const DETAIL_HANDBOOK_ACTIONS = {
  FETCH_DETAIL_HANDBOOK_LOADING: "FETCH_DETAIL_HANDBOOK_LOADING",
  FETCH_DETAIL_HANDBOOK_SUCCESS: "FETCH_DETAIL_HANDBOOK_SUCCESS",
  FETCH_DETAIL_HANDBOOK_ERROR: "FETCH_DETAIL_HANDBOOK_ERROR",
};

export default DETAIL_HANDBOOK_ACTIONS;
