const PROFILE_ACTIONS = {
  FETCH_USER_INFO_LOADING: "FETCH_USER_INFO_LOADING",
  FETCH_USER_INFO_SUCCESS: "FETCH_USER_INFO_SUCCESS",
  FETCH_USER_INFO_ERROR: "FETCH_USER_INFO_ERROR",
  FETCH_USER_CHILDS_LOADING: "FETCH_USER_CHILDS_LOADING",
  FETCH_USER_CHILDS_SUCCESS: "FETCH_USER_CHILDS_SUCCESS",
  FETCH_USER_CHILDS_ERROR: "FETCH_USER_CHILDS_ERROR",
};

export default PROFILE_ACTIONS;
