const TRACKING_MILK_ACTIONS = {
  FETCH_MILK_NOTES_LOADING: "FETCH_MILK_NOTES_LOADING",
  FETCH_MILK_NOTES_SUCCESS: "FETCH_MILK_NOTES_SUCCESS",
  FETCH_MILK_NOTES_ERROR: "FETCH_MILK_NOTES_ERROR",
  REFRESH_MILK_NOTES: "REFRESH_MILK_NOTES",
  SHOW_MILK_NOTES_MODAL: "SHOW_MILK_NOTES_MODAL",
  FETCH_MILK_NOTE_DETAIL_LOADING: "FETCH_MILK_NOTE_DETAIL_LOADING",
  FETCH_MILK_NOTE_DETAIL_SUCCESS: "FETCH_MILK_NOTE_DETAIL_SUCCESS",
  FETCH_MILK_NOTE_DETAIL_ERROR: "FETCH_MILK_NOTE_DETAIL_ERROR",
};

export default TRACKING_MILK_ACTIONS;
