const FORGOT_PASSWORD_ACTIONS = {
  SEND_RESET_PASSWORD_EMAIL_LOADING: "SEND_RESET_PASSWORD_EMAIL_LOADING",
  SEND_RESET_PASSWORD_EMAIL_SUCCESS: "SEND_RESET_PASSWORD_EMAIL_SUCCESS",
  SEND_RESET_PASSWORD_EMAIL_ERROR: "SEND_RESET_PASSWORD_EMAIL_ERROR",
  SAVE_EMAIL: "SAVE_EMAIL",
  REENTER_EMAIL: "REENTER_EMAIL",
};

export default FORGOT_PASSWORD_ACTIONS;
