const ROUTERS = {
  LOGIN: "/dang-nhap",
  REGISTER: "/dang-ki",
  HANDBOOK: "/cam-nang",
  STORIES: "/khoanh-khac",
  FAQ: "/hoi-dap",
  FORGOT_PASSWORD: "/quen-mat-khau",
  RESET_PASSWORD: "/reset-mat-khau",
  PROFILE: "/tai-khoan",
  ACTIVITY_TRACK: "/theo-doi-hoat-dong",
  HOME: "/",
  TRACKING_HEIGHT: "/theo-doi-hoat-dong/chieu-cao",
  TRACKING_WEIGHT: "/theo-doi-hoat-dong/can-nang",
  TRACKING_VACCIN: "/theo-doi-hoat-dong/tiem-chung",
  TRACKING_MILK: "/theo-doi-hoat-dong/luong-sua",
  TRACKING_WEAN: "/theo-doi-hoat-dong/an-dam",
  CALENDAR: "/theo-doi-hoat-dong/hoat-dong",
  CHAT: "/tin-nhan",
  PROFILE_INFO: "/tai-khoan/thong-tin",
  PROFILE_STORY: "/tai-khoan/khoanh-khac-cua-ban",
  PROFILE_BLOCKED_USER: "/tai-khoan/nguoi-dung-da-chan",
  CHILD_MANAGE: "/tai-khoan/thong-tin-cua-be",
  PROFILE_CHILD: "/tai-khoan/danh-sach-be",
};

export default ROUTERS;
