import CONSTANTS from "@/constants";

export const NOTE_TYPE = {
  HEIGHT: CONSTANTS.ROUTERS.TRACKING_HEIGHT,
  WEIGHT: CONSTANTS.ROUTERS.TRACKING_WEIGHT,
  VACCIN: CONSTANTS.ROUTERS.TRACKING_VACCIN,
  MILK_TIME: CONSTANTS.ROUTERS.TRACKING_MILK,
  WEAN: CONSTANTS.ROUTERS.TRACKING_WEAN,
};

export const NOTE_TYPE_LABEL = {
  [NOTE_TYPE.HEIGHT]: "Chiều cao",
  [NOTE_TYPE.WEIGHT]: "Cân nặng",
  [NOTE_TYPE.MILK_TIME]: "Lượng sữa",
  [NOTE_TYPE.VACCIN]: "Lịch tiêm chủng",
  [NOTE_TYPE.WEAN]: "Ăn dặm",
};
