const CHILD_MANAGE_ACTIONS = {
  FETCH_CHILD_DETAIL_LOADING: "FETCH_CHILD_DETAIL_LOADING",
  FETCH_CHILD_DETAIL_SUCCESS: "FETCH_CHILD_DETAIL_SUCCESS",
  FETCH_CHILD_DETAIL_ERROR: "FETCH_CHILD_DETAIL_ERROR",
  UPDATE_CHILD_DETAIL: "UPDATE_CHILD_DETAIL",
  ADD_CHILD: "ADD_CHILD",
  UPDATE_SCREEN_MODE: "UPDATE_SCREEN_MODE",
  SUBMIT_CHILD_LOADING: "SUBMIT_CHILD_LOADING",
  SUBMIT_CHILD_SUCCESS: "SUBMIT_CHILD_SUCCESS",
  SUBMIT_CHILD_ERROR: "SUBMIT_CHILD_ERROR",
  UPLOAD_AVATAR_LOADING: "UPLOAD_AVATAR_LOADING",
  UPLOAD_AVATAR_SUCCESS: "UPLOAD_AVATAR_SUCCESS",
  UPLOAD_AVATAR_ERROR: "UPLOAD_AVATAR_ERROR",
  UPLOAD_COVER_LOADING: "UPLOAD_COVER_LOADING",
  UPLOAD_COVER_SUCCESS: "UPLOAD_COVER_SUCCESS",
  UPLOAD_COVER_ERROR: "UPLOAD_COVER_ERROR",
};

export default CHILD_MANAGE_ACTIONS;
