const TRACKING_ACTIVITY_ACTIONS = {
  FETCH_ACTIVITY_NOTES_LOADING: "FETCH_ACTIVITY_NOTES_LOADING",
  FETCH_ACTIVITY_NOTES_SUCCESS: "FETCH_ACTIVITY_NOTES_SUCCESS",
  FETCH_ACTIVITY_NOTES_ERROR: "FETCH_ACTIVITY_NOTES_ERROR",
  REFRESH_ACTIVITY_NOTES: "REFRESH_ACTIVITY_NOTES",
  SHOW_ACTIVITY_NOTES_MODAL: "SHOW_ACTIVITY_NOTES_MODAL",
  FETCH_ACTIVITY_NOTE_DETAIL_LOADING: "FETCH_ACTIVITY_NOTE_DETAIL_LOADING",
  FETCH_ACTIVITY_NOTE_DETAIL_SUCCESS: "FETCH_ACTIVITY_NOTE_DETAIL_SUCCESS",
  FETCH_ACTIVITY_NOTE_DETAIL_ERROR: "FETCH_ACTIVITY_NOTE_DETAIL_ERROR",
  SELECT_DATE: "SELECT_DATE",
};

export default TRACKING_ACTIVITY_ACTIONS;
