const PROFILE_STORY_ACTIONS = {
  FETCH_PROFILE_STORY_LOADING: "FETCH_PROFILE_STORY_LOADING",
  FETCH_PROFILE_STORY_SUCCESS: "FETCH_PROFILE_STORY_SUCCESS",
  FETCH_PROFILE_STORY_ERROR: "FETCH_PROFILE_STORY_ERROR",
  SHOW_STORY_MODAL: "SHOW_STORY_MODAL",
  UPDATE_MODAL_DATA: "UPDATE_MODAL_DATA",
  DELETE_STORY: "DELETE_STORY",
};

export default PROFILE_STORY_ACTIONS;
