const STORY_DETAIL_ACTIONS = {
  FETCH_STORY_DETAIL_LOADING: "FETCH_STORY_DETAIL_LOADING",
  FETCH_STORY_DETAIL_SUCCESS: "FETCH_STORY_DETAIL_SUCCESS",
  FETCH_STORY_DETAIL_ERROR: "FETCH_STORY_DETAIL_ERROR",
  FETCH_COMMENTS_LOADING: "FETCH_COMMENTS_LOADING",
  FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
  FETCH_COMMENTS_ERROR: "FETCH_COMMENTS_ERROR",
  LIKE_STORY: "LIKE_STORY",
  DISLIKE_STORY: "DISLIKE_STORY",
  REFRESH_COMMENTS: "REFRESH_COMMENTS",
  SET_BASE_COMMENT: "SET_BASE_COMMENT",
  TRIGGER_RELOAD_SUB_COMMENT: "TRIGGER_RELOAD_SUB_COMMENT",
  SHOW_LIKER_MODAL: "SHOW_LIKER_MODAL",
  REFRESH_STORY_DETAIL: "REFRESH_STORY_DETAIL",
};

export default STORY_DETAIL_ACTIONS;
