const TRACKING_HEIGHT_ACTIONS = {
  FETCH_HEIGHT_NOTES_LOADING: "FETCH_HEIGHT_NOTES_LOADING",
  FETCH_HEIGHT_NOTES_SUCCESS: "FETCH_HEIGHT_NOTES_SUCCESS",
  FETCH_HEIGHT_NOTES_ERROR: "FETCH_HEIGHT_NOTES_ERROR",
  REFRESH_HEIGHT_NOTES: "REFRESH_HEIGHT_NOTES",
  SHOW_HEIGHT_NOTES_MODAL: "SHOW_HEIGHT_NOTES_MODAL",
  FETCH_HEIGHT_NOTE_DETAIL_LOADING: "FETCH_HEIGHT_NOTE_DETAIL_LOADING",
  FETCH_HEIGHT_NOTE_DETAIL_SUCCESS: "FETCH_HEIGHT_NOTE_DETAIL_SUCCESS",
  FETCH_HEIGHT_NOTE_DETAIL_ERROR: "FETCH_HEIGHT_NOTE_DETAIL_ERROR",
};

export default TRACKING_HEIGHT_ACTIONS;
