const HANDBOOK_ACTIONS = {
  FETCH_HANDBOOK_LOADING: "FETCH_HANDBOOK_LOADING",
  FETCH_HANDBOOK_SUCCESS: "FETCH_HANDBOOK_SUCCESS",
  FETCH_HANDBOOK_ERROR: "FETCH_HANDBOOK_ERROR",
  FETCH_CATEGORIES_LOADING: "FETCH_CATEGORIES_LOADING",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_ERROR: "FETCH_CATEGORIES_ERROR",
  REFRESH_HANDBOOK_LIST: "REFRESH_HANDBOOK_LIST",
  SET_FILTER_CATEGORY: "SET_FILTER_CATEGORY",
  RESET_HANDBOOK_LIST: "RESET_HANDBOOK_LIST",
  TRIGGER_SEARCH_HANDBOOK: "TRIGGER_SEARCH_HANDBOOK",
};

export default HANDBOOK_ACTIONS;
